Add Micronaut port
coherence-community/todo-list-example pull request #3
Opened 2021-01-11 17:52 UTC by vasac

2021-01-14 21:10 UTC, aseovic requested changes
Looks good overall, but there are a number of smaller changes that need to be made.

Also, please make sure that all the files in the PR use 2021 in the copyright headers.

2021-01-14 21:10 UTC, aseovic commented on java/micronaut-server/src/main/k8s/ingress.yaml
> +          serviceName: todo-list-http
change to `todo-list-micronaut-server-http`

2021-01-14 21:10 UTC, aseovic commented on java/micronaut-server/src/main/k8s/ingress.yaml
> +  - host: grpc.tasks.synoki.io
change to `grpc.tasks.micronaut.coherence.community`

2021-01-14 21:10 UTC, aseovic commented on java/micronaut-server/src/main/k8s/ingress.yaml
> +          serviceName: todo-list-grpc
change to `todo-list-micronaut-server-grpc`

2021-01-14 21:10 UTC, aseovic commented on java/micronaut-server/src/main/resources/application.yml
> +    name: todoListMicronautServer
change to `todo-list-micronaut-server`

2021-01-14 21:10 UTC, aseovic commented on java/micronaut-server/src/main/resources/application.yml
> +    port: 3000
do you need to specify the port? isn't 3000 the default port?

2021-01-14 21:10 UTC, aseovic commented on java/micronaut-server/src/main/resources/logback.xml
> +            <pattern>%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n</pattern>
Do we need to do any work to make Coherence log output look similar to standard Micronaut output?

We did that for Helidon...

2021-01-15 03:32 UTC, vasac commented on java/micronaut-server/src/main/resources/application.yml
> +    port: 3000
8080 is the default Micronaut port.

2021-01-15 19:50 UTC, aseovic approved these changes

2021-01-15 19:51 UTC, merged